version: "3.3"
services:
  db:
    image: mongo:latest
    deploy:
      restart_policy:
        condition: on-failure
  server:
    image: ambrosia-server:latest
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      - PORT=8000
      - DB_URL=mongodb://db:27017
    deploy:
      restart_policy:
        condition: on-failure
  client:
    image: ambrosia-client:latest
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "3000:80"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    deploy:
      restart_policy:
        condition: on-failure
